#ifndef DOSBOXCUSTOM
#define DOSBOXCUSTOM

#define DOSBOXCUSTOM_APPNAME "Supaplex"
#define DOSBOXCUSTOM_VERSION ""
#define DOSBOXCUSTOM_EXECUTABLE "spfix63/spfix63.exe"
#define DOSBOXCUSTOM_CONFIGFILE "dosbox.conf"

#define DOSBOXCUSTOM_VIDEOMODE 0xd
#define DOSBOXCUSTOM_NOVIDEOCHANGE
#define DOSBOXCUSTOM_WIDTH 320
#define DOSBOXCUSTOM_HEIGHT 200
#define DOSBOXCUSTOM_NOCONSOLE

#endif
